### ISSUE TITLE
More friendly EOL description

### ISSUE THREAD

**Issue by bluebruce** [atom/line-ending-selector#14]
It will be more user friendly to add "Windows" or "Unix" description on both UI and convert menu.
For example, change:
LF to Unix(LF)
CRLF to Windows(CRLF)
CR to Old Mac(CR)

**Comment by GuillaumeLegendre** [comment]
Maybe add the sentence character too \r\n or \n or...

edit: I mean in the part who appear after we click on the LF in the status bar

**Comment by lee-dohm** [comment]
I feel like status-bar space is at a premium. Perhaps changing the text in the selection menu and then adding a tooltip for when hovering over the control in the status bar?

**Comment by GuillaumeLegendre** [comment]
Exactly like I expect it in better. My english didn't allow me to explain it well.

**Comment by bronson** [comment]
Would https://github.com/atom/line-ending-selector/pull/42 address this issue?

(assuming we can agree on wording...)

**Comment by bluebruce** [comment]
@bronson Great solution! Works without taking status-bar space.

**Comment by bronson** [comment]
Well, it's not merged yet...  But I admire your confidence.  :)

**Comment by bluebruce** [comment]
OK. then I wait. :) Will github notify me when merged? (I'm a newbie).

**Comment by bronson** [comment]
If I included `Fixes #14` in the commit message, github would automatically close this issue and notify you when the PR is merged.

But I wasn't sure so I didn't include it.

You can subscribe to the pull request if you want to watch its progress.  Or I'll comment here when it's merged or rejected.

**Comment by bronson** [comment]
I said I'd comment but I'm sure you've already seen that this is merged and closed @bluebruce.  Thanks @damieng!
