### ISSUE TITLE
Atom and/or package line-ending-select use inconsistent terminology - term 'status-bar'

### ISSUE THREAD

**Issue by afischli** [atom/line-ending-selector#21]
The Atom 1.3.3 package 'line-ending-select' refers to the 'status-bar', but no menu command of Atom contains the phrase 'status-bar' and nowhere do I see something like a status bar. Moreover, Atom Help (from menu bar) does not know the term 'status-bar'. Searching on line for help by following help link 'For help, please visit: • The 'Atom docs' for Guides and the API reference' brings me to https://atom.io/docs. There I a search for 'status-bar' finds finally something, 4 web pages. Link '1.3 Getting Started : Atom Basics' looks best, however, searching on that page (https://atom.io/docs/v1.4.0/getting-started-atom-basics) for 'status-bar' fails: 'Not found'. Something is wrong here.

**Comment by lee-dohm** [comment]
It is referring to the [status-bar package](https://atom.io/packages/status-bar). It is true that we interchangeably use the package name form "status-bar", the title-cased form "Status Bar" and sometimes even "status bar". Other than these various forms, I think that we pretty consistently use the words "status bar" to refer to the UI generated by the status-bar package.

Other than that, this appears to be a documentation request? Would you mind clarifying what you're looking for?

**Comment by afischli** [comment]
Sure but I do not know what is correct, since this was my first attempt at evaluating Atom and learning to know it a bit. However, I do for sure know this: I would like to have consistency throughout. What I hate are things as MicroSoft Word offers, e.g. a specialized term close to jargon used in a menu command, but when you search for it, e.g. in the help mechanism of Word, you never find it. Of you find some help text, as was the case now with Atom package 'line-ending-select' using term 'status-bar', but you don't find that explained anywhere, since the introductory text uses 'status bar' (as I now learned later). 

But I do not know what is the more common term, 'status bar' or 'status-bar'. Having learned more about Atom I now know what it is and I now know that both terms are used in various places. Whichever it is, that one should be used throughout help texts, menu commands, guides, tutorials etc. so that Atom uses always one single term consistently. Then searching for it is easy and one finds the wanted explanations quickly. At least I would have wasted considerably less time in trying to understand what that status bar ought to be and where it can be found on my Atom screen. 

Sorry for not being able to tell you exactly what the best solution is. If status-bar is correct, then the getting started text needs to be fixed. Otherwise, if status bar is correct, the help of the package line-ending-select needs to be updated.

**Comment by lee-dohm** [comment]
I've opened a tracking issue for this since it is far more than just the line-ending-selector package that is going to need changing. Thanks for bringing this up!

**Comment by afischli** [comment]
Thank you.
