### ISSUE TITLE
Unable to change line endings from CR to anything else

### ISSUE THREAD

**Issue by lparsons** [atom/line-ending-selector#29]
Atom loads the file correctly, and displays the line ending format as `CR`. However, when I click on `CR` and select either `LF` or `CRLF`, nothing happens.

**Comment by alexchandel** [comment]
Confirmed. What's the point of even showing the CR if it's broken?

This should be able to convert the file to LF or CRLF.

**Comment by lparsons** [comment]
To be clear, the CR is correct (and useful). These files are indeed using the old Mac OS line endings, `\r`. It's just that I would like to change the line endings to UNIX format `\n`.

**Comment by maxbrunsfeld** [comment]
I would  have thought https://github.com/atom/line-ending-selector/pull/27 would fix this. Are you still experiencing this problem on the latest Atom?

**Comment by lparsons** [comment]
This works now in version Atom version 1.9.0 and line-ending-selector 0.5.0. When I submitted the report, version 1.8.0 was the latest and it was broken there. Thanks for the fix!
