### ISSUE TITLE
Allow Normalize File EOL's On Save

### ISSUE THREAD

**Issue by NodeJoSe** [atom/line-ending-selector#36]
Hello! im having some trouble with atom-beautify changing my line ending format from lf to crlf and vice versa, depending if im using jsbeautify or prettydiff.

I managed to solve the issue by using "Normalize File EOL's On Save" feature of the "line-ending-converter" package, but that package is not maintained because we have line ending selector now :)

We should add this feature on the line-ending-selector package!

**Comment by bronson** [comment]
Apologies for not understanding...  If jsbeautify or prettydiff are changing your line endings, isn't that an issue with those packages?

**Comment by walterdeboer** [comment]
I guess the bug is for those packages, but the feature is missing in line-ending-selector, so that sounds like a feature request :-)
