### ISSUE TITLE
Show unknown line endings

### ISSUE THREAD

**Issue by Arcanemagus** [atom/line-ending-selector#4]
If a file is set to CR line endings (ancient mac style) this plugin has no idea what is going on and reports it as whatever the file was before conversion to CR.

Reproduce:
1. Install [line-ending-converter](https://atom.io/packages/line-ending-converter)
2. Use that to switch the file to CR endings

(Or any other method of your choice)

**Comment by maxbrunsfeld** [comment]
Yeah, this case is not covered. It would be good (and easy to add) to detect CR line endings properly. I probably wouldn't want to offer `CR` line endings in the selector though.

**Comment by Arcanemagus** [comment]
I agree with you that it shouldn't really offer that, the only reason I even found out it didn't support it was testing whether it was a viable replacement for the package I was using before :wink:.
