### ISSUE TITLE
atom.packages.onDidActivateInitialPackages is deprecated.

### ISSUE THREAD

**Issue by Stanzilla** [atom/line-ending-selector#40]
You have the core package "line-ending-selector" installed as a community package. See https://github.com/atom/dalek for how this causes problems and instructions on how to correct the situation.
```
atom.packages.onDidActivateInitialPackages (C:\Users\Benjamin\AppData\Local\atom\app-1.16.0-beta0\resources\app.asar\node_modules\dalek\lib\main.js:14:14)
Function.module.exports.Emitter.simpleDispatch (C:\Users\Benjamin\AppData\Local\atom\app-1.16.0-beta0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
Emitter.emit (C:\Users\Benjamin\AppData\Local\atom\app-1.16.0-beta0\resources\app.asar\node_modules\event-kit\lib\emitter.js:129:28)
<unknown> (C:\Users\Benjamin\AppData\Local\atom\app-1.16.0-beta0\resources\app.asar\src\package-manager.js:514:32)
```

**Comment by lee-dohm** [comment]
@Stanzilla Please follow the directions at the link you indicate. You have the core package "line-ending-selector" installed as a community package.

**Comment by Stanzilla** [comment]
Oh oops, didn't even read what it said, so used to the automatic issue submission doing the right thing(TM). Maybe it should not offer to report that for stuff dalek detects? @lee-dohm

**Comment by lee-dohm** [comment]
@Stanzilla Agreed. There are a few things that we should update about deprecation-cop but I figured getting the dalek package out was more important and we can clean up deprecation-cop later.
