### ISSUE TITLE
Add setting to set default line-endings for new files

### ISSUE THREAD

**Issue by clintwood** [atom/line-ending-selector#5]
Hi, I work on Windows but always use just LF.  Since this landed all my new files are by default CRLF which is not what I want.  

Please add a setting to override the platform default for new files.  Actually, ideally, an override per file extension type :)

**Comment by traverse** [comment]
:+1: Would be awesome because having to convert from CRLF to LF for every new file I create is getting tedious.

**Comment by BujiasBitwise** [comment]
I would also like to see this.

**Comment by jonasahlsson** [comment]
I am too a Windows user looking for a way to set default to LF. 

Thanks in advance!

**Comment by hho** [comment]
:+1: 

In fact, we don't need a setting. Just make sure the default is _always_ LF. It's not 1995 anymore, even Windows can now handle ".cmd" batch files with LF line endings.

**Comment by Calinou** [comment]
> It's not 1995 anymore, even Windows can now handle ".cmd" batch files with LF line endings.

I think `notepad.exe` in Windows 7/8/8.1/10 still can't display files with LF line endings properly, though; it sadly remains the default text editor on Windows.

**Comment by fbourigault** [comment]
:+1: 
I'm using atom and vagrant to dev symfony2 apps so I will never want a file ending with CRLF !

**Comment by Keavon** [comment]
Please add this, it's pretty easy to forget to set it to LF from CRLF when making new files.

**Comment by davidspiess** [comment]
I would also like to have this setting! 
As a workaournd you can create a `.editorconfig` file with something like this

```
# EditorConfig is awesome: http://EditorConfig.org

# top-most EditorConfig file
root = true

# Unix-style newlines with a newline ending every file
[*]
end_of_line = lf
insert_final_newline = true
```

And install the following plugin https://github.com/sindresorhus/atom-editorconfig

**Comment by oh-ren** [comment]
Thanks for sharing @davidspiess, will look into that.
There's also this: https://atom.io/packages/line-ending-selector-unix (remember to disable the built-in package).

\+ in the meantime, let's wait for an update on PR #7?

**Comment by SOSANA** [comment]
@davidspiess Where do we put  ```.editorconfi``` once we install it?

**Comment by keweilizhe** [comment]
i have solution now.

You can change the default line ending setting for new files within Atom.

Atom version 1.0.8 introduced the line ending selector package which allows you to change the line ending setting for the current file by selecting LR (Unix based) or CRLF (Windows based) within the Atom status bar.

This is useful for existing files, but by default for new files the package will use the OS default (LF on Unix, CRLF on Windows). It is recommended in general that you use LF line endings throughout. To change the default line endings for new files, follow these steps:

Select File->Settings
Select ‘Packages’
Under Core Packages->line-ending-selector, select ‘Settings’
Under the ‘Default line ending’ setting, choose ‘LF’ in the dropdown
You new files will now use LF as the default line ending setting. You can confirm this in the Atom status bar.

reference:   http://developmentsindigital.com/atom/2016/08/27/setting-atom-default-line-endings/

**Comment by rsn8887** [comment]
This is useless if you want to change the line ending on just a single line, which seems to be impossible in Atom.
