### ISSUE TITLE
Uncaught TypeError: object is not a function

### ISSUE THREAD

**Issue by monkpit** [atom/line-ending-selector#9]
I just installed Atom on my Ubuntu laptop and the first thing I see is this error message.
I haven't installed any extra packages or even opened a file yet.

Steps to reproduce:
1. Install Atom
2. Open Atom

**Atom Version**: 1.0.15
**System**: Ubuntu 14.10
**Thrown From**: [line-ending-selector](https://github.com/atom/line-ending-selector) package, v0.0.5
### Stack Trace

Uncaught TypeError: object is not a function

```
At /usr/share/atom/resources/app.asar/node_modules/line-ending-selector/lib/main.js:74

TypeError: object is not a function
    at Object.consumeStatusBar (/usr/share/atom/resources/app.asar/node_modules/line-ending-selector/lib/main.js:74:23)
    at Provider.module.exports.Provider.provide (/usr/share/atom/resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
    at /usr/share/atom/resources/app.asar/node_modules/service-hub/lib/service-hub.js:55:26
    at doNTCallback0 (node.js:416:9)
    at process._tickCallback (node.js:345:13)
```
### Commands

```
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by izuzak** [comment]
cc @maxbrunsfeld for :eyes:

**Comment by maxbrunsfeld** [comment]
@monkpit It seems like something is wrong with your install of Atom. How did you install it?

Can you open the developer tools (`ctrl-shift-i` on Linux), select the `Sources` tab, and open the following file, and share its contents (maybe in a gist)?

`atom/resources/app.asar/node_modules/line-ending-selector/lib/status-bar-item.js`

**Comment by monkpit** [comment]
I installed by downloading the .deb from the front page of atom.io.

The file you referenced does not exist (which is probably a problem...)

The files I have under atom/resources/app.asar/node_modules/line-ending-selector/lib are:
line-ending-list-view.js
main.js

And that's all.

I have the missing files from github, can I add them to app.asar somehow? I tried to open it as an archive and didn't get anywhere with that...

**Comment by maxbrunsfeld** [comment]
I just downloaded the 1.0.15 debian package and I can see the `status-bar-item.js` in the asar file. Can you try re-downloading it?

>  I tried to open it as an archive and didn't get anywhere with that...

Yeah, I'm not sure how to do that, but the `app.asar` file can be viewed as plain text; it's basically just a bunch of files concatenated together, with a single line of JSON at the top indicating the offset of each file.

**Comment by monkpit** [comment]
I am not able to view the file /usr/share/atom/resources/app.asar as text in Atom or in Sublime Text 3. Both are showing it as a binary format.

I must be doing something really incorrectly but I can't find out what it is.
I reinstalled the .deb I initially downloaded, that didn't work.
I've re-downloaded and reinstalled the .deb with no luck there either.
I'm currently in the process of compiling from source.

By the way, the .deb I installed from is atom-amd64.deb - is this the same one you checked?

**Comment by maxbrunsfeld** [comment]
> I am not able to view the file /usr/share/atom/resources/app.asar as text in Atom or in Sublime Text 3. Both are showing it as a binary format.

It does start with some binary data. Try `less` or `vim`.

> I've re-downloaded and reinstalled the .deb with no luck there either.

Ok, there must be something else wrong with this file. Trying it on Ubuntu now.

**Comment by maxbrunsfeld** [comment]
Ok, I just installed the package on Ubuntu 14.04 and I can run it with no problem. Can you report the output of this command?

``` sh
sha1sum ~/Downloads/atom-amd64.deb # or wherever you downloaded the file to
```

The sha1 should be:

``` sh
859321d24274d8ddda974b028a5dfd09b12d8898
```

**Comment by monkpit** [comment]
After building from source the source version works fine. The .deb version still raises the error.

SHA1 matches expected value, `859321d24274d8ddda974b028a5dfd09b12d8898`

So after verifying the checksum I did a full uninstall again, did a reinstall with the known good hash .deb file, and I still get the issue.

I have no clue what could be going on here, but my source build I have living in /opt works A-OK now.

If you want any further info to try to solve the issue I'll be happy to give assistance and keep the problem version around on my machine.

Thanks for your assistance Max!

**Comment by gerred** [comment]
I'm getting this as well in 15.10 with 1.0.19

My SHA1 for that release is: 42b48eeefa2e92d08345cea1f13c78d247483d4f

**Comment by gophercoders** [comment]
I've see this as well on Ubuntu 15.04, also with the 1.019 release.

After some fiddling around the fix seems easy though. Just quit atom then delete atom's cache with

`rm -rf ~/.atom/compile-cache`

from your (bash) shell. Restart atom and things are fine again.

**Comment by damieng** [comment]
Haven't seen any additional reports of this for a year, closing.
